export const SET_VIDEOGAMES = 'SET_VIDEOGAMES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_VIDEOGAME = 'SET_VIDEOGAME';
export const FETCH_VIDEOGAME_REQUEST = 'FETCH_VIDEOGAME_REQUEST';
export const FETCH_VIDEOGAME_SUCCESS = 'FETCH_VIDEOGAME_SUCCESS';
export const FETCH_VIDEOGAME_FAILURE = 'FETCH_VIDEOGAME_FAILURE';
export const SET_GENRES = 'SET_GENRES';
export const SET_ACCESS = 'SET_ACCESS';
export const BUSCAR_JUEGO_POR_NOMBRE = "BUSCAR_JUEGO_POR_NOMBRE";

export const ADD_VIDEOGAME_REQUEST = "ADD_VIDEOGAME_REQUEST";
export const ADD_VIDEOGAME_SUCCESS = "ADD_VIDEOGAME_SUCCESS";
export const ADD_VIDEOGAME_FAILURE = "ADD_VIDEOGAME_FAILURE";
